// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import rehypeExternalLinks from 'rehype-external-links';
import remarkWikilinks from './plugins/remark-wikilinks.mjs';
import {
  ENABLED_LANGUAGE_CODES,
  DEFAULT_LANGUAGE,
} from './src/config/languages.mjs';
import { readdirSync, statSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// 2026-04-24 β3: Build existing URL set from src/content/ to filter sitemap
// hreflang alternate to only include actually-existing language versions.
// Without this, @astrojs/sitemap auto-generates hreflang for ALL enabled
// locales for EVERY page — causing 1,705+ fake hreflang URLs (Google crawls
// them → 404 → SC reports 404). This pre-build scan + serialize() hook fix
// the systemic SEO leak.
//
// URL mapping convention:
//   src/content/{lang}/{category}/{slug}.md →
//     {lang === 'zh-TW' ? '' : '/' + lang}/{category}/{slug}/
function buildExistingUrlSet() {
  const set = new Set();
  const contentRoot = './src/content';
  for (const lang of ENABLED_LANGUAGE_CODES) {
    const langPath = join(contentRoot, lang);
    if (!existsSync(langPath)) continue;
    let cats;
    try {
      cats = readdirSync(langPath);
    } catch {
      continue;
    }
    for (const cat of cats) {
      const catPath = join(langPath, cat);
      let isDir = false;
      try {
        isDir = statSync(catPath).isDirectory();
      } catch {
        continue;
      }
      if (!isDir) continue;
      let files;
      try {
        files = readdirSync(catPath);
      } catch {
        continue;
      }
      for (const f of files) {
        if (!f.endsWith('.md')) continue;
        if (f.startsWith('_')) continue; // skip _Hub etc
        const slug = f.replace(/\.md$/, '');
        const prefix = lang === DEFAULT_LANGUAGE.code ? '' : `/${lang}`;
        set.add(`${prefix}/${cat}/${slug}/`);
      }
    }
    // Also add language landing pages (/en/, /ja/, /ko/) and zh-TW root
    const prefix = lang === DEFAULT_LANGUAGE.code ? '/' : `/${lang}/`;
    set.add(prefix);
  }
  return set;
}

const existingUrlSet = buildExistingUrlSet();
console.log(
  `[sitemap-hreflang-filter] Loaded ${existingUrlSet.size} existing URL paths for hreflang validation`,
);

// Build sitemap i18n locales map: { 'zh-TW': 'zh-TW', en: 'en', ... }
const sitemapLocales = Object.fromEntries(
  ENABLED_LANGUAGE_CODES.map((code) => [code, code]),
);

// 2026-04-18 δ-late (upstream): Taiwan.md's Semiont pages were zh-TW-only.
// Header nav's translatePath() generates /en/semiont/*, /ja/semiont/*, /ko/semiont/*
// etc. even though those routes don't exist — causing systemic 404s.
//
// 2026-06-22: re-grounded for LagunaBeach.md. All 7 routes below now load this
// project's own re-grounded *.en.md docs (see docs/semiont/, Phase 5) and are
// English-canonical at the unprefixed default route, not zh-TW. This redirect
// list still exists because `zh-TW` is `enabled: true` in languages.ts but has
// no actual page route — without it, /zh-TW/semiont/* would 404 instead of
// landing on the real (English) page. /semiont/diary is the one genuine
// exception: diary entries are written live, per session, in zh-TW, and stay
// that way by design (see src/i18n/semiont.ts header comment).
const SEMIONT_ROUTES = [
  '/semiont/manifesto',
  '/semiont/dna',
  '/semiont/anatomy',
  '/semiont/consciousness',
  '/semiont/heartbeat',
  '/semiont/unknowns',
  '/semiont/longings',
  '/semiont/diary', // entries are zh-TW only; landing notice points readers there
];
const NON_DEFAULT_LANGS = ENABLED_LANGUAGE_CODES.filter(
  (c) => c !== DEFAULT_LANGUAGE.code,
);
const semiontRedirects = Object.fromEntries(
  NON_DEFAULT_LANGS.flatMap((lang) =>
    SEMIONT_ROUTES.map((route) => [`/${lang}${route}`, `${route}/`]),
  ),
);

// 2026-06-07 SEO freshness (reports/seo-optimization-plan-2026-06-07.md §1.1):
// Per-URL sitemap <lastmod> from real last-meaningful-commit dates, generated by
// scripts/core/build-content-dates.mjs (git-derived, cosmetic-filtered). Replaces
// the old global `lastmod: new Date()` which made Google distrust our lastmod.
let contentDates = {};
try {
  contentDates =
    JSON.parse(readFileSync('./src/data/content-dates.json', 'utf-8')).dates ||
    {};
} catch {
  // not yet generated → omit lastmod entirely (safe; never fake-fresh)
}

export default defineConfig({
  site: 'https://lagunabeach.md',
  integrations: [
    sitemap({
      changefreq: 'weekly',
      priority: 0.7,
      // 2026-06-07: global `lastmod: new Date()` REMOVED — it made every page
      // claim "modified today" on every build, the exact anti-pattern Google
      // names (→ distrusts our lastmod site-wide). lastmod is now set per-URL in
      // serialize() from content-dates.json. See SEO plan report §1.1.
      // Customize priority and changefreq for different pages
      customPages: ['https://lagunabeach.md/?changefreq=daily&priority=1.0'],
      i18n: {
        defaultLocale: DEFAULT_LANGUAGE.code,
        locales: sitemapLocales,
      },
      // 2026-04-24 β3: Filter hreflang alternate links to only include
      // actually-existing language versions. Without this filter,
      // @astrojs/sitemap auto-generates alternate hreflang for ALL enabled
      // locales for EVERY page—even when the target language version doesn't
      // exist—causing systemic 404s reported in Search Console.
      //
      // Pre-fix data: 3,031 hreflang tags vs 1,800 actual content files
      //   → 1,705 fake hreflang (en +675 / ja +432 / ko +598)
      //
      // serialize() runs per sitemap item before XML emission. We filter
      // item.links to only include alternates whose path exists in
      // existingUrlSet (built from src/content/ filesystem scan above).
      serialize(item) {
        // Per-URL <lastmod> = real last meaningful edit (content-dates.json,
        // git-derived + cosmetic-filtered). Omit when unknown — never fake.
        // decodeURIComponent: sitemap loc percent-encodes CJK slugs (zh-TW
        // articles), but content-dates keys are raw UTF-8 — decode to match.
        try {
          const lm =
            contentDates[decodeURIComponent(new URL(item.url).pathname)];
          if (lm) item.lastmod = lm;
          else delete item.lastmod;
        } catch {
          delete item.lastmod;
        }
        if (!item.links || item.links.length === 0) return item;
        const filteredLinks = item.links.filter((link) => {
          try {
            const path = new URL(link.url).pathname;
            return existingUrlSet.has(path);
          } catch {
            // Malformed URL; drop conservatively
            return false;
          }
        });
        // Astro types: links is optional; empty array is fine but undefined
        // signals "no alternate" cleanly
        item.links = filteredLinks.length > 0 ? filteredLinks : undefined;
        return item;
      },
    }),
  ],
  i18n: {
    defaultLocale: DEFAULT_LANGUAGE.code,
    locales: [...ENABLED_LANGUAGE_CODES],
    routing: {
      prefixDefaultLocale: false,
    },
  },
  // 2026-04-11 heartbeat: Static redirects for top 404 URLs identified via
  // Cloudflare logs. Astro generates HTML meta-refresh pages for each entry.
  // Review with: bash scripts/tools/fetch-cloudflare.py --days 1
  redirects: {
    // Taiwan.md content-merge / 404 redirects removed during the LagunaBeach.md
    // migration — their source and target URLs do not exist here. Only the semiont
    // meta-page language redirects remain (those /semiont/* pages are still present).
    ...semiontRedirects,
  },
  // 2026-05-04: build perf tuning. Page render is 93% of build time
  // (363s render / 391s wall, baseline 4,331 pages). concurrency 1 → 4
  // is the highest-ROI lever; details in reports/research/astro-build-speed-2026-05-04.md.
  // 2026-06-10 audit A/B: 8,436 頁 / 943s render，有效平行度 3.08/4 → 試 8。
  // heap 已 12GB；下個 CI build 看 wall + RSS，OOM/變慢即回退 4。
  // reports/build-pipeline-audit-2026-06-10.md 熱點 #2a。
  build: {
    concurrency: 8,
    inlineStylesheets: 'auto',
  },
  markdown: {
    // Explicit lang allowlist. Knowledge corpus uses bare ``` fences almost
    // exclusively (1 named lang in src/content), so capping the loaded grammar
    // bundle to common ones keeps Shiki startup small without breaking pages.
    shikiConfig: {
      theme: 'github-light',
      wrap: true,
      langs: [
        'ts',
        'tsx',
        'js',
        'jsx',
        'astro',
        'bash',
        'sh',
        'md',
        'json',
        'yaml',
        'html',
        'css',
        'python',
        'go',
        'rust',
        'sql',
        'diff',
        'plaintext',
      ],
    },
    remarkPlugins: [remarkWikilinks],
    rehypePlugins: [
      [
        rehypeExternalLinks,
        { target: '_blank', rel: ['noopener', 'noreferrer'] },
      ],
    ],
  },
  vite: {
    plugins: [tailwindcss()],
    build: {
      target: 'es2022',
      minify: 'esbuild',
      cssCodeSplit: true,
      chunkSizeWarningLimit: 10000,
      rollupOptions: {
        output: {
          // For huge SSG (4k+ pages) Rollup spends measurable time computing
          // chunk splits when the per-route bundle is tiny. Forcing one-chunk
          // output is faster on this scale (per bitdoze 339k-page case study).
          manualChunks: undefined,
        },
      },
    },
    esbuild: {
      target: 'es2022',
      minifyIdentifiers: false,
      minifySyntax: true,
      minifyWhitespace: true,
    },
    optimizeDeps: { force: false },
  },
  // experimental.queuedRendering tested 2026-05-04 — local wallclock unchanged,
  // peak RSS 1.7 GB → 4.3 GB (poolSize: 1000 over-allocates for diverse pages).
  // Skipping until upstream tunes pool sizing for content-heavy SSG.
});
