#!/bin/bash
# Taiwan.md Daily Stats Update
# Run by cron at midnight daily
#
# ⚠️ IMPORTANT: This script MUST NOT modify about.template.astro
# The contributors grid is managed separately to avoid destroying
# Sponsors + Contact sections (happened 3 times already).
# Stats go into: README.md, src/i18n/about.ts, public/api/stats.json
set -e
cd "$(dirname "$0")/../.."

# Cross-platform in-place sed (BSD/macOS needs `-i ''`, GNU/Linux needs `-i`).
# 2026-06-13: the old hardcoded `sed -i ''` silently failed on CI ubuntu (GNU
# sed reads '' as the script), so README/about.ts never updated there — part of
# why the stats sat stale. sedi detects GNU sed via --version.
sedi() {
  if sed --version >/dev/null 2>&1; then sed -i "$@"; else sed -i '' "$@"; fi
}

echo "📊 Updating Taiwan.md stats..."

# 1. Stars/forks: dashboard-vitals.json SSOT (generate-dashboard-data.js fetches
#    them once with soft-fail preserve — the SAME source the about page reads, so
#    README / about / dashboard never diverge). 2026-06-13: was a direct `gh api`
#    call here — a second stars source that needed gh auth (absent in CI) and could
#    drift from the about value. Now this script needs no GitHub auth at all.
STARS=$(python3 -c "import json;print(json.load(open('public/api/dashboard-vitals.json')).get('stars',0))" 2>/dev/null || echo 0)
FORKS=$(python3 -c "import json;print(json.load(open('public/api/dashboard-vitals.json')).get('forks',0))" 2>/dev/null || echo 0)
# Contributors: contributors.json SSOT (GitHub /contributors API, refreshed
# every prebuild by generate-contributors-data.js — the SAME source the about
# page's data-driven grid reads, so README / about / dashboard stay consistent).
# 2026-06-13: was .all-contributorsrc (manual, a month stale at 57). contributors.json
# .totals.contributors is the live committer count; fall back to the rc file → 30.
CONTRIBUTORS=$(python3 -c "import json;print(json.load(open('public/api/contributors.json'))['totals']['contributors'])" 2>/dev/null || grep -c '"login"' .all-contributorsrc 2>/dev/null || echo 30)
# 各語言精確文章數（zh = 大寫分類目錄無 lang prefix；其他 = knowledge/{lang}/）。
# 舊版 ZH_PAGES 用 `! -path '*/en/*'` 把 ja/ko/es/fr 全算進 zh（3977 假數）— 修正。
ZH_PAGES=$(find knowledge -maxdepth 2 -name '*.md' ! -name '_*' -regex 'knowledge/[A-Z][a-zA-Z]*/.*' | wc -l | tr -d ' ')
EN_PAGES=$(find knowledge/en -name '*.md' ! -name '_*' 2>/dev/null | wc -l | tr -d ' ')
JA_PAGES=$(find knowledge/ja -name '*.md' ! -name '_*' 2>/dev/null | wc -l | tr -d ' ')
KO_PAGES=$(find knowledge/ko -name '*.md' ! -name '_*' 2>/dev/null | wc -l | tr -d ' ')
ES_PAGES=$(find knowledge/es -name '*.md' ! -name '_*' 2>/dev/null | wc -l | tr -d ' ')
FR_PAGES=$(find knowledge/fr -name '*.md' ! -name '_*' 2>/dev/null | wc -l | tr -d ' ')
TOTAL_PAGES=$ZH_PAGES
# 近 7/30 天新文章：dashboard-vitals.json（routine 算好），fallback 0
D7=$(python3 -c "import json;print(json.load(open('public/api/dashboard-vitals.json')).get('articlesLast7Days',0))" 2>/dev/null || echo 0)
D30=$(python3 -c "import json;print(json.load(open('public/api/dashboard-vitals.json')).get('articlesLast30Days',0))" 2>/dev/null || echo 0)

echo "Stars: $STARS | Forks: $FORKS | Contributors: $CONTRIBUTORS"
echo "zh:$ZH_PAGES en:$EN_PAGES ja:$JA_PAGES ko:$KO_PAGES es:$ES_PAGES fr:$FR_PAGES | 7d:$D7 30d:$D30"

# 2. Regenerate README stats table between STATS:START/END markers.
# 2026-06-13: full-block regen replaces the old per-row sed, which had drifted
# off README's row names (only Contributors still matched → whole table sat
# stale). Markers make it row-name-agnostic — robust against future renames.
python3 - "$ZH_PAGES" "$EN_PAGES" "$JA_PAGES" "$KO_PAGES" "$ES_PAGES" "$FR_PAGES" "$CONTRIBUTORS" "$STARS" "$FORKS" "$D7" "$D30" <<'PYEOF'
import sys, re
zh, en, ja, ko, es, fr, contrib, stars, forks, d7, d30 = sys.argv[1:12]
rows = [
    ("📄 Total articles (zh-TW SSOT)", zh),
    ("🇹🇼 Chinese (zh-TW)", zh),
    ("🇺🇸 English (en)", en),
    ("🇯🇵 日本語 (ja)", ja),
    ("🇰🇷 한국어 (ko)", ko),
    ("🇪🇸 Español (es)", es),
    ("🇫🇷 Français (fr)", fr),
    ("📂 Categories", "14"),
    ("🕸️ Knowledge graph nodes", "220+"),
    ("🔗 Resource websites", "146+"),
    ("👥 Contributors", contrib),
    ("⭐ GitHub Stars", stars),
    ("🍴 Forks", forks),
    ("📅 Articles last 7 days", d7),
    ("📅 Articles last 30 days", d30),
]
table = "| Metric | Count |\n| --- | --- |\n" + "\n".join(f"| {m} | {c} |" for m, c in rows)
block = (
    "<!-- STATS:START — auto-generated by scripts/tools/update-stats.sh from SSOT "
    "(knowledge/ + contributors.json + dashboard-vitals.json). "
    "Do not edit by hand. -->\n\n" + table + "\n\n<!-- STATS:END -->"
)
readme = open("README.md").read()
if "<!-- STATS:START" not in readme:
    print("⚠️  README has no STATS markers — skipping (add them first)")
else:
    readme = re.sub(r"<!-- STATS:START.*?STATS:END -->", block, readme, flags=re.S)
    open("README.md", "w").write(readme)
    print("✅ README stats table regenerated")
PYEOF

# 2b. Regenerate the README all-contributors table from contributors.json.
# 2026-06-13: this used to be hand-maintained .all-contributorsrc (no bot — the
# rc file sat a month stale). Now both the table and about's grid read the same
# auto-generated SSOT (committers + git-inferred types ∪ rc curated overlay), so
# README stays in sync without anyone running the all-contributors CLI.
python3 - <<'PYEOF'
import json, re

try:
    ac = json.load(open("public/api/contributors.json")).get("allContributors", [])
except Exception:
    ac = []

if ac:
    cells = [
        f'<td align="center"><a href="{c["profileUrl"]}"><img src="{c["avatarUrl"]}" '
        f'width="100px;" alt=""/><br /><sub><b>{c.get("name", c["login"])}</b></sub></a>'
        f'<br />{" ".join(c.get("types", []))}</td>'
        for c in ac
    ]
    rows = [
        "  <tr>\n    " + "\n    ".join(cells[i : i + 7]) + "\n  </tr>"
        for i in range(0, len(cells), 7)
    ]
    table = "<table>\n" + "\n".join(rows) + "\n</table>"
    block = (
        "<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->\n"
        + table
        + "\n<!-- ALL-CONTRIBUTORS-LIST:END -->"
    )
    readme = open("README.md").read()
    if "<!-- ALL-CONTRIBUTORS-LIST:START" in readme:
        readme = re.sub(
            r"<!-- ALL-CONTRIBUTORS-LIST:START.*?ALL-CONTRIBUTORS-LIST:END -->",
            block,
            readme,
            flags=re.S,
        )
        open("README.md", "w").write(readme)
        print(f"✅ README all-contributors table regenerated ({len(ac)} people)")
    else:
        print("⚠️  README has no ALL-CONTRIBUTORS markers — skipping")
PYEOF

# 3. Update about page stats via i18n (NOT the template!)
# Round stars to nearest 100
if [ "$STARS" -ge 1000 ]; then
  STARS_DISPLAY="$(echo "$STARS" | sed 's/..$//')00+"
elif [ "$STARS" -ge 100 ]; then
  STARS_DISPLAY="$(echo "$STARS" | sed 's/.$//')0+"
else
  STARS_DISPLAY="${STARS}+"
fi

PAGES_DISPLAY="${TOTAL_PAGES}+"
CONTRIBUTORS_DISPLAY="${CONTRIBUTORS}+"

# Update i18n stats (safe — only changes string values)
sedi "s/'about.stats.pages.number': '[^']*'/'about.stats.pages.number': '${PAGES_DISPLAY}'/g" src/i18n/about.ts
sedi "s/'about.stats.stars.number': '[^']*'/'about.stats.stars.number': '${STARS_DISPLAY}'/g" src/i18n/about.ts
sedi "s/'about.stats.contributors.number': '[^']*'/'about.stats.contributors.number': '${CONTRIBUTORS_DISPLAY}'/g" src/i18n/about.ts

# 4. Merge GitHub stats into public/api/stats.json (preserve existing fields!)
# stats.json is primarily generated by generate-content-stats.js with rich data
# (categories, tags, etc). We only update the GitHub-sourced fields here.
python3 << PYEOF
import json, os
stats_path = 'public/api/stats.json'
if os.path.exists(stats_path):
    with open(stats_path) as f:
        stats = json.load(f)
else:
    stats = {}
# Only update GitHub-sourced fields, preserve everything else
stats['stars'] = $STARS
stats['forks'] = $FORKS
stats['estimatedContributors'] = $CONTRIBUTORS
stats['zhPages'] = $ZH_PAGES
stats['enPages'] = $EN_PAGES
stats['totalPages'] = $TOTAL_PAGES
with open(stats_path, 'w') as f:
    json.dump(stats, f, indent=2, ensure_ascii=False)
print("✅ stats.json merged (preserved existing fields)")
PYEOF

# 5. Generate content stats
node scripts/tools/generate-content-stats.js 2>/dev/null || true

echo "✅ Stats updated: ⭐${STARS} 🍴${FORKS} 👥${CONTRIBUTORS} 📄${TOTAL_PAGES}"
echo ""
echo "⚠️ about.template.astro was NOT touched (by design)."
echo "   Contributors grid is updated by the separate Contributors Update cron."
