/**
 * contributors.ts — per-article git provenance, read from the PREBUILT
 * src/data/git-info.json (NOT from a live git subprocess).
 *
 * 2026-06-13 EVO-A4: the git pass moved entirely into prebuild
 * (scripts/core/build-git-info.mjs). The astro render stage now has ZERO git
 * dependency — buildGitInfoCache() reads the prebuilt JSON. This is the
 * structural endgame of the 2026-06-13 per-render-scope lesson: not just
 * memoize the git pass (Fable's fix, 4,697 → 6 subprocesses), but remove it
 * from the render stage altogether (6 → 0). Same Map<absPath, GitInfo>
 * interface, so article.template.astro + the 6 [slug] wrappers are untouched.
 *
 * resolveContributor / contributor-profile resolution moved to the prebuild
 * script (its correct home — build-time-only, zero render-time consumers).
 *
 * Trade-off (unchanged from before): a dev server holding the loaded JSON
 * won't reflect new commits until prebuild reruns — same as content-dates.json
 * and articles-index.ts. A static build is one process with a fixed JSON, so
 * no effect on production output.
 */
import { readFileSync } from 'fs';
import { resolve } from 'path';

export type Contributor = {
  name: string;
  login: string;
};

export type GitInfo = {
  contributors: Contributor[];
  lastModified: string;
  commitHash: string;
  revisionCount: number;
};

export function emptyGitInfo(): GitInfo {
  return {
    contributors: [],
    lastModified: '',
    commitHash: '',
    revisionCount: 0,
  };
}

// Prebuilt provenance, keyed by repo-relative NFC path ('knowledge/en/Art/x.md').
// Loaded dynamically (NOT static import) so a missing git-info.json — e.g. a raw
// `astro dev` that skipped prebuild:gitinfo — degrades to empty sidebars rather
// than a vite resolve error. git-info.json is gitignored (1.5 MB, churns on
// every knowledge/ commit — wrong fit for git tracking), regenerated by
// prebuild:gitinfo in both the dev and build chains.
function loadGitInfoFiles(): Record<string, GitInfo> {
  try {
    const raw = readFileSync(
      resolve(process.cwd(), 'src/data/git-info.json'),
      'utf-8',
    );
    return (JSON.parse(raw) as { files?: Record<string, GitInfo> }).files || {};
  } catch {
    return {};
  }
}
const _files = loadGitInfoFiles();

// Per-knowledgePath memo, preserving the old buildGitInfoCache() interface.
// Consumers query the returned Map by ABSOLUTE NFC path, so we re-derive
// abs keys with resolve(cwd, relPath) exactly as the old code did.
const _cacheByPath = new Map<string, Map<string, GitInfo>>();

/**
 * Returns Map<absPath, GitInfo> for every article file under `knowledgePath`.
 * Prefix semantics match the OLD git pathspec exactly:
 *   'knowledge/'      → all languages (zh wrappers; keys never collide because
 *                        consumers query by full absolute path)
 *   'knowledge/en/'   → English only
 */
export function buildGitInfoCache(knowledgePath: string): Map<string, GitInfo> {
  const memo = _cacheByPath.get(knowledgePath);
  if (memo) return memo;

  const prefix = knowledgePath.endsWith('/')
    ? knowledgePath
    : `${knowledgePath}/`;
  const cache = new Map<string, GitInfo>();
  for (const relPath in _files) {
    if (!relPath.startsWith(prefix)) continue;
    const absKey = resolve(process.cwd(), relPath).normalize('NFC');
    cache.set(absKey, _files[relPath]);
  }

  _cacheByPath.set(knowledgePath, cache);
  return cache;
}
