import { useTranslations } from '../i18n/utils';

// 22 縣市系列 route — Tier 1 evolution（hard-coded coords，pending Tier 2 lat/lon frontmatter）
const COUNTIES_22_ROUTE = {
  id: 'counties22',
  name: '📍 22 縣市深度文章',
  description:
    '走訪 Taiwan.md 22 篇縣市深度文章，從基隆 pilot 到新北 finale — 每個縣市一條核心矛盾。',
  color: '#16a34a',
  // ship 順序：pilot 基隆 → finale 新北
  stops: [
    {
      id: 'c22-keelung',
      name: '基隆市',
      lat: 25.131,
      lng: 121.741,
      note: '離台北最近的港口，最被台北看不見',
      link: '/geography/基隆市',
    },
    {
      id: 'c22-chiayi-city',
      name: '嘉義市',
      lat: 23.477,
      lng: 120.452,
      note: '被皇帝賜名嘉義，卻成了最容易被略過的省轄市',
      link: '/geography/嘉義市',
    },
    {
      id: 'c22-lienchiang',
      name: '連江縣',
      lat: 26.158,
      lng: 119.951,
      note: '離台灣最遠的縣，是離冷戰最近的縣',
      link: '/geography/連江縣',
    },
    {
      id: 'c22-penghu',
      name: '澎湖縣',
      lat: 23.566,
      lng: 119.563,
      note: '兩次拒博弈，澎湖選擇的不是清貧',
      link: '/geography/澎湖縣',
    },
    {
      id: 'c22-yilan',
      name: '宜蘭縣',
      lat: 24.752,
      lng: 121.755,
      note: '兩次選擇了自己的命運，蘭陽平原從此沒回頭',
      link: '/geography/宜蘭縣',
    },
    {
      id: 'c22-miaoli',
      name: '苗栗縣',
      lat: 24.561,
      lng: 120.821,
      note: '客家硬頸的縣，用八年選出讓縣庫翻倍負債的縣長',
      link: '/geography/苗栗縣',
    },
    {
      id: 'c22-hsinchu-county',
      name: '新竹縣',
      lat: 24.836,
      lng: 121.012,
      note: '235 年義民信仰與全台第一人均所得，同住頭前溪',
      link: '/geography/新竹縣',
    },
    {
      id: 'c22-chiayi-county',
      name: '嘉義縣',
      lat: 23.452,
      lng: 120.685,
      note: '49 萬人把全國的臉借給阿里山，自己卻找不到臉',
      link: '/geography/嘉義縣',
    },
    {
      id: 'c22-pingtung',
      name: '屏東縣',
      lat: 22.668,
      lng: 120.488,
      note: '國家命運轉折發生在這裡，台北從來沒怎麼記得',
      link: '/geography/屏東縣',
    },
    {
      id: 'c22-hualien',
      name: '花蓮縣',
      lat: 23.987,
      lng: 121.601,
      note: '129 年隱身撒奇萊雅族，用正名換回的太魯閣，0403 又遠去',
      link: '/geography/花蓮縣',
    },
    {
      id: 'c22-taitung',
      name: '臺東縣',
      lat: 22.755,
      lng: 121.144,
      note: '兩個離島，一個關了 36 年政治犯，一個存了 42 年核廢料',
      link: '/geography/台東縣',
    },
    {
      id: 'c22-changhua',
      name: '彰化縣',
      lat: 24.075,
      lng: 120.543,
      note: '打敗過杜邦，留不住年輕人的農業大縣',
      link: '/geography/彰化縣',
    },
    {
      id: 'c22-yunlin',
      name: '雲林縣',
      lat: 23.706,
      lng: 120.434,
      note: '宜蘭選擇不要的，雲林用三十年的肺換下來',
      link: '/geography/雲林縣',
    },
    {
      id: 'c22-kinmen',
      name: '金門縣',
      lat: 24.448,
      lng: 118.317,
      note: '1949 那 56 小時，決定金門 75 年的命運——也決定了台灣',
      link: '/geography/金門縣',
    },
    {
      id: 'c22-nantou',
      name: '南投縣',
      lat: 23.961,
      lng: 120.972,
      note: '震央在集集，賽德克的血在霧社，省政府的形在中興新村',
      link: '/geography/南投縣',
    },
    {
      id: 'c22-hsinchu-city',
      name: '新竹市',
      lat: 24.804,
      lng: 120.969,
      note: '1733 種竹為城的竹塹，1980 長出台積電的搖籃，差了 247 年',
      link: '/geography/新竹市',
    },
    {
      id: 'c22-taoyuan',
      name: '桃園市',
      lat: 24.993,
      lng: 121.301,
      note: '台灣的進出口、最多的客家、最多的移工，全在這塊台地',
      link: '/geography/桃園市',
    },
    {
      id: 'c22-tainan',
      name: '臺南市',
      lat: 22.992,
      lng: 120.221,
      note: '261 年首府、400 年古蹟、21 世紀晶片，疊在同一片土地',
      link: '/geography/台南市',
    },
    {
      id: 'c22-kaohsiung',
      name: '高雄市',
      lat: 22.627,
      lng: 120.302,
      note: '1979 同一年升格直轄市，也爆發了美麗島事件',
      link: '/geography/高雄市',
    },
    {
      id: 'c22-taipei',
      name: '臺北市',
      lat: 25.038,
      lng: 121.564,
      note: '萬華 1738 / 大稻埕 1885 / 信義 2004——12 區活在不同世紀',
      link: '/geography/台北市',
    },
    {
      id: 'c22-taichung',
      name: '臺中市',
      lat: 24.144,
      lng: 120.679,
      note: '1887 差點當首都，2010 才升格直轄市，等了 123 年',
      link: '/geography/台中市',
    },
    {
      id: 'c22-new-taipei',
      name: '新北市',
      lat: 25.012,
      lng: 121.466,
      note: '包圍台北的環狀都會，1629 紅毛城比台北建城早 200 年',
      link: '/geography/新北市',
    },
  ],
};

export function getMapRoutes(t: ReturnType<typeof useTranslations>) {
  return [
    COUNTIES_22_ROUTE,
    {
      id: 'nightMarkets',
      name: t('map.routes.nightMarkets.name'),
      description: t('map.routes.nightMarkets.description'),
      color: '#f39c12',
      stops: [
        {
          id: 'shilinNightMarket',
          name: t('map.stops.shilinNightMarket.name'),
          lat: 25.088,
          lng: 121.524,
          note: t('map.stops.shilinNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'raoheNightMarket',
          name: t('map.stops.raoheNightMarket.name'),
          lat: 25.051,
          lng: 121.577,
          note: t('map.stops.raoheNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'ningxiaNightMarket',
          name: t('map.stops.ningxiaNightMarket.name'),
          lat: 25.056,
          lng: 121.515,
          note: t('map.stops.ningxiaNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'fengjiaNightMarket',
          name: t('map.stops.fengjiaNightMarket.name'),
          lat: 24.179,
          lng: 120.647,
          note: t('map.stops.fengjiaNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'huayuanNightMarket',
          name: t('map.stops.huayuanNightMarket.name'),
          lat: 23.004,
          lng: 120.206,
          note: t('map.stops.huayuanNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'liuheNightMarket',
          name: t('map.stops.liuheNightMarket.name'),
          lat: 22.632,
          lng: 120.299,
          note: t('map.stops.liuheNightMarket.note'),
          link: '/food/夜市文化',
        },
      ],
    },
    {
      id: 'nationalParks',
      name: t('map.routes.nationalParks.name'),
      description: t('map.routes.nationalParks.description'),
      color: '#27ae60',
      stops: [
        {
          id: 'yangmingshanNationalPark',
          name: t('map.stops.yangmingshanNationalPark.name'),
          lat: 25.158,
          lng: 121.549,
          note: t('map.stops.yangmingshanNationalPark.note'),
          link: '/nature/國家公園',
        },
        {
          id: 'tarokoNationalPark',
          name: t('map.stops.tarokoNationalPark.name'),
          lat: 24.158,
          lng: 121.621,
          note: t('map.stops.tarokoNationalPark.note'),
          link: '/nature/國家公園',
        },
        {
          id: 'yushanNationalPark',
          name: t('map.stops.yushanNationalPark.name'),
          lat: 23.47,
          lng: 120.957,
          note: t('map.stops.yushanNationalPark.note'),
          link: '/nature/國家公園',
        },
        {
          id: 'alishanScenicArea',
          name: t('map.stops.alishanScenicArea.name'),
          lat: 23.51,
          lng: 120.7,
          note: t('map.stops.alishanScenicArea.note'),
          link: '/nature/阿里山',
        },
        {
          id: 'sunMoonLakeScenicArea',
          name: t('map.stops.sunMoonLakeScenicArea.name'),
          lat: 23.863,
          lng: 120.917,
          note: t('map.stops.sunMoonLakeScenicArea.note'),
          link: '/nature/日月潭',
        },
        {
          id: 'kentingNationalPark',
          name: t('map.stops.kentingNationalPark.name'),
          lat: 21.948,
          lng: 120.803,
          note: t('map.stops.kentingNationalPark.note'),
          link: '/nature/國家公園',
        },
      ],
    },
    {
      id: 'historyTrail',
      name: t('map.routes.historyTrail.name'),
      description: t('map.routes.historyTrail.description'),
      color: '#e74c3c',
      stops: [
        {
          id: 'anpingFort',
          name: t('map.stops.anpingFort.name'),
          lat: 22.998,
          lng: 120.161,
          note: t('map.stops.anpingFort.note'),
          link: '/history/荷蘭與西班牙殖民時期',
        },
        {
          id: 'chikanTower',
          name: t('map.stops.chikanTower.name'),
          lat: 22.998,
          lng: 120.203,
          note: t('map.stops.chikanTower.note'),
          link: '/history/鄭氏時期',
        },
        {
          id: 'lukang',
          name: t('map.stops.lukang.name'),
          lat: 24.055,
          lng: 120.437,
          note: t('map.stops.lukang.note'),
          link: '/culture/鹿港',
        },
        {
          id: 'presidentialOffice',
          name: t('map.stops.presidentialOffice.name'),
          lat: 25.04,
          lng: 121.512,
          note: t('map.stops.presidentialOffice.note'),
          link: '/history/日本殖民統治',
        },
        {
          id: 'chiangKaiShekMemorialHall',
          name: t('map.stops.chiangKaiShekMemorialHall.name'),
          lat: 25.036,
          lng: 121.522,
          note: t('map.stops.chiangKaiShekMemorialHall.note'),
          link: '/history/戒嚴時期',
        },
        {
          id: 'legislativeYuan',
          name: t('map.stops.legislativeYuan.name'),
          lat: 25.044,
          lng: 121.521,
          note: t('map.stops.legislativeYuan.note'),
          link: '/society/太陽花學運',
        },
      ],
    },
    {
      id: 'oldStreets',
      name: t('map.routes.oldStreets.name'),
      description: t('map.routes.oldStreets.description'),
      color: '#9b59b6',
      stops: [
        {
          id: 'dihuaStreet',
          name: t('map.stops.dihuaStreet.name'),
          lat: 25.057,
          lng: 121.51,
          note: t('map.stops.dihuaStreet.note'),
          link: '/culture/大稻埕',
        },
        {
          id: 'jiufenOldStreet',
          name: t('map.stops.jiufenOldStreet.name'),
          lat: 25.109,
          lng: 121.845,
          note: t('map.stops.jiufenOldStreet.note'),
          link: '/culture/九份',
        },
        {
          id: 'lukangOldStreet',
          name: t('map.stops.lukangOldStreet.name'),
          lat: 24.055,
          lng: 120.437,
          note: t('map.stops.lukangOldStreet.note'),
          link: '/culture/鹿港',
        },
        {
          id: 'anpingOldStreet',
          name: t('map.stops.anpingOldStreet.name'),
          lat: 22.998,
          lng: 120.161,
          note: t('map.stops.anpingOldStreet.note'),
          link: '/history/安平',
        },
        {
          id: 'qishanOldStreet',
          name: t('map.stops.qishanOldStreet.name'),
          lat: 22.889,
          lng: 120.483,
          note: t('map.stops.qishanOldStreet.note'),
          link: '/culture/旗山',
        },
        {
          id: 'tamsuiOldStreet',
          name: t('map.stops.tamsuiOldStreet.name'),
          lat: 25.17,
          lng: 121.44,
          note: t('map.stops.tamsuiOldStreet.note'),
          link: '/culture/淡水',
        },
      ],
    },
  ];
}
